### ISSUE TITLE
Doesn't work with MicroPython 1.18

### ISSUE THREAD

**Issue by ilium007** [CrankshawNZ/Micropython#1]
Just for anyone looking at using this, it no longer works with current MicroPython I2C class. Various errors:

ie.
`AttributeError: 'I2C' object has no attribute 'mem_read_into'`

**Comment by ilium007** [comment]
My bad. I had imported the I2C class from 'pyb' not 'machine'. Works fine.
